services:
  mergerfs:
    image: "cr.hotio.dev/hotio/mergerfs"
    container_name: "mergerfs"
    privileged: true
    devices:
      - "/dev/fuse:/dev/fuse"
    volumes:
      - "/media/daniel/K7G9K5ZL:/mnt/disk1:shared"
      - "/media/daniel/V6J9VPHS:/mnt/disk2:shared"
      - "/mnt/storage:/mnt/storage:shared"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "UMASK=022"
      - "MFS_SRC=/mnt/disk1:/mnt/disk2"
      - "MFS_DEST=/mnt/storage"
      - "MFS_OPTIONS=defaults,allow_other,cache.files=off,use_ino,dropcacheonclose=true,category.create=mfs,minfreespace=20G"
    restart: "always"

  snapraid:
    image: "lscr.io/linuxserver/snapraid:latest"
    container_name: "snapraid"
    volumes:
      - "/home/daniel/docker-nas/snapraid/snapraid.conf:/config/snapraid.conf"
      - "/media/daniel/K7G9K5ZL:/media/daniel/K7G9K5ZL"
      - "/media/daniel/V6J9VPHS:/media/daniel/V6J9VPHS"
      - "/media/daniel/ZC1DPCTH:/media/daniel/ZC1DPCTH"
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
    restart: "unless-stopped"

  filebrowser:
    image: "filebrowser/filebrowser:latest"
    container_name: "cloud_filebrowser"
    user: "1000:1000"
    ports:
      - "8081:80"
    volumes:
      - "/mnt/storage:/srv"
      - "/home/daniel/docker-nas/filebrowser.db:/database.db"
    restart: "always"
