# SnapRAID Konfiguration
# Paritätsdatei (auf der größten Platte)
parity /media/daniel/ZC1DPCTH/snapraid.parity

# Content-Dateien (Listen der Dateien, auf mehreren Platten verteilt)
content /var/snapraid/snapraid.content
content /media/daniel/K7G9K5ZL/snapraid.content
content /media/daniel/V6J9VPHS/snapraid.content

# Daten-Platten
data d1 /media/daniel/K7G9K5ZL/
data d2 /media/daniel/V6J9VPHS/

# Ausschlüsse (optionale Dateitypen, die nicht gesichert werden müssen)
exclude /lost+found/
exclude /tmp/
exclude .AppleDouble
exclude ._ *
exclude .Thumbs.db
exclude .DS_Store
